### ISSUE TITLE
CI: 'SpecifierSet' object has no attribute 'split'

### ISSUE THREAD

**Issue by shortmann** [pycontribs/molecule-azure#4]
Currently the Travis build job is not working.
It looks like the same problem
https://github.com/ansible/molecule/issues/2350
```
================================== log start ===================================
Obtaining file:///home/travis/build/pycontribs/molecule-azure
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/travis/build/pycontribs/molecule-azure/setup.py", line 330, in <module>
        setuptools.setup(**setup_params)
      File "/tmp/pip-build-env-bwij6tlu/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/opt/python/3.7.1/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-bwij6tlu/lib/python3.7/site-packages/setuptools/dist.py", line 447, in __init__
        k: v for k, v in attrs.items()
      File "/opt/python/3.7.1/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-bwij6tlu/lib/python3.7/site-packages/setuptools/dist.py", line 735, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-bwij6tlu/lib/python3.7/site-packages/setuptools/dist.py", line 291, in check_specifier
        packaging.specifiers.SpecifierSet(value)
      File "/tmp/pip-build-env-bwij6tlu/lib/python3.7/site-packages/setuptools/_vendor/packaging/specifiers.py", line 594, in __init__
        specifiers = [s.strip() for s in specifiers.split(",") if s.strip()]
    AttributeError: 'SpecifierSet' object has no attribute 'split'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/travis/build/pycontribs/molecule-azure/
=================================== log end ====================================
```

**Comment by decentral1se** [comment]
Yep, pain isn't it? ;)

You'll find some answers over @ https://github.com/ansible/molecule/issues/2350

:ambulance:

**Comment by shortmann** [comment]
Well, I fixed it like bristea @ https://github.com/ansible/molecule/pull/2381
But the unit tests are not working. I need more time to understand how the new plugin/driver system should work. ;-)

**Comment by decentral1se** [comment]
Noice. I got the unit tests working for my latest work on the Hetzner Cloud plugin over @ https://github.com/pycontribs/molecule-hetznercloud. It's very minimal for now but will do while we keep working on porting things out. Maybe that can help for now.

**Comment by ssbarnea** [comment]
Fixed in master.
